---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discoveryserver-springboot
  labels:
    app: discoveryserver-springboot
    app-log-type: json-logging-app
    decode_log_event_to_json_object: "true"
    collect_logs_with_filebeat: "true"
  namespace: dev
  annotations:
    co.elastic.logs.food-ordering-demo-springboot/json.keys_under_root: "true"
    co.elastic.logs.food-ordering-demo-springboot/json.add_error_key: "true"
    co.elastic.logs.food-ordering-demo-springboot/json.message_key: "message"
spec:
  serviceName: discoveryserver-springboot
  replicas: 1
  selector:
    matchLabels:
      app: discoveryserver-springboot
  template:
    metadata:
      labels:
        app: discoveryserver-springboot
        app-log-type: json-logging-app
        decode_log_event_to_json_object: "true"
        collect_logs_with_filebeat: "true"
      annotations:
        co.elastic.logs.food-ordering-demo-springboot/json.keys_under_root: "true"
        co.elastic.logs.food-ordering-demo-springboot/json.add_error_key: "true"
        co.elastic.logs.food-ordering-demo-springboot/json.message_key: "message"
    spec:
      containers:
      - name: discoveryserver-springboot
        image: ${NEXUS_REPO_HOST}/digitalbiohumans/poc/discovery-server-eureka-springboot:0.0.7.1-spring-cloud-config-secure-client-SNAPSHOT
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev-secure
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://food-ordering-springboot-cloud-config:8888
        ports:
        - name: port-tcp
          containerPort: 8761
          protocol: TCP
        - name: port-udp
          containerPort: 8761
          protocol: UDP
        livenessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: discoveryserver-springboot
  labels:
    app: discoveryserver-springboot
  namespace: dev
spec:
  ports:
  - name: gateway-port
    port: 8761
    targetPort: 8761
  type: ClusterIP
  selector:
    app: discoveryserver-springboot
---